os: linux
dist: trusty
# See https://github.com/travis-ci/travis-ci/issues/8378 ; remove later
group: deprecated-2017Q3
python:
    - '3.6'
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -y cpanminus hunspell myspell-en-gb node npm perl libhunspell-dev libio-all-perl libperl-dev
install:
    - gem install sass compass compass-blueprint
    - sudo cpanm Alien::Tidyp YAML::XS
    - sudo cpanm --force HTML::Tidy
    - sudo cpanm HTML::Spelling::Site MooX MooX::late Perl::Critic Perl::Tidy Test::Code::TidyAll Test::HTML::Recursive::DeprecatedTags Test::HTML::Tidy::Recursive::Strict Test::TrailingSpace
    - npm uninstall babel -g
    - "( cd open-web-dev-tools/ && `which npm` install -g babel-cli babel-preset-env babel-preset-es2015 requirejs qunit-cli typescript typings uglify-es )"
    - "( cd open-web-dev-tools/ && `which npm` install babel-preset-env babel-preset-react babel-preset-stage-2 requirejs uglify-es )"
script:
    - cd open-web-dev-tools/ && perl gen-helpers.pl && make && make test
