os: linux
dist: trusty
# See https://github.com/travis-ci/travis-ci/issues/8378 ; remove later
group: deprecated-2017Q3
python:
    - '3.6'
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -y node npm perl libio-all-perl yui-compressor
    - sudo ln -s /usr/bin/yui-compressor /usr/bin/yuicompressor
install:
    - gem install sass compass compass-blueprint
    - cpanm --force HTML::Tidy
    - cpanm MooX Test::HTML::Recursive::DeprecatedTags Test::HTML::Tidy::Recursive Test::TrailingSpace
    - npm uninstall babel -g
    - "( cd open-web-dev-tools/ && `which npm` install -g babel-cli babel-preset-env babel-preset-es2015 qunit-cli typescript typings )"
    - "( cd open-web-dev-tools/ && `which npm` install babel-preset-env babel-preset-react babel-preset-stage-2 )"
script:
    - cd open-web-dev-tools/ && perl gen-helpers.pl && make && make test
